# Generated by Django 4.2.1 on 2023-06-06 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0003_remove_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='idUsuario',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='idusuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
