# Generated by Django 4.2.1 on 2023-06-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0007_publicacion_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='estatus',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='fechaComentario',
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fechaPublicacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
