# Generated by Django 4.2.1 on 2023-06-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0009_comentario_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='fotoPerfil',
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil'),
        ),
    ]
