# Generated by Django 4.2.1 on 2023-06-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0010_remove_perfil_fotoperfil_perfil_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='foto_perfil',
        ),
    ]
