# Generated by Django 4.2.1 on 2023-06-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0011_remove_perfil_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil'),
        ),
    ]
