# Generated by Django 4.2.1 on 2023-06-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0012_perfil_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(default='default.jpg', upload_to='perfil'),
        ),
    ]
