# Generated by Django 4.2.1 on 2023-06-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0013_alter_perfil_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
