# Generated by Django 4.2.1 on 2023-06-20 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0016_publicacion_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
