# Generated by Django 4.2.1 on 2023-07-05 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0017_delete_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='fechaCreacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
